=== monkey1sai/l2j-server-datapack/src/main/resources/data/xsd/instance.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="instance">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="activityTime" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="val" type="xs:positiveInteger"
							use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="allowSummon" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="val" type="xs:boolean" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="emptyDestroyTime" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="val" type="xs:positiveInteger"
							use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="PvPInstance" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="val" type="xs:boolean" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="showTimer" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="val" type="xs:boolean" use="required" />
						<xs:attribute name="increase" type="xs:boolean" />
						<xs:attribute name="text" type="xs:normalizedString" />
					</xs:complexType>
				</xs:element>
				<xs:element name="spawnPoints" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Location" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="x" type="xs:int" use="required" />
									<xs:attribute name="y" type="xs:int" use="required" />
									<xs:attribute name="z" type="xs:int" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="startPosType" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="FIXED" />
									<xs:enumeration value="RANDOM" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="exitPoint" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="x" type="xs:int" use="required" />
						<xs:attribute name="y" type="xs:int" use="required" />
						<xs:attribute name="z" type="xs:int" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="reenter" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="reset" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="day">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="Monday" />
												<xs:enumeration value="Tuesday" />
												<xs:enumeration value="Wednesday" />
												<xs:enumeration value="Thursday" />
												<xs:enumeration value="Friday" />
												<xs:enumeration value="Saturday" />
												<xs:enumeration value="Sunday" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="time" type="xs:long" />
									<xs:attribute name="hour" type="xs:positiveInteger" />
									<xs:attribute name="minute" type="xs:positiveInteger" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="additionStyle">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="NONE" />
									<xs:enumeration value="ON_INSTANCE_ENTER" />
									<xs:enumeration value="ON_INSTANCE_FINISH" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="removeBuffs" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="skill" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" type="xs:integer" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="type">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="ALL" />
									<xs:enumeration value="WHITELIST" />
									<xs:enumeration value="BLACKLIST" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="doorlist" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="door" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="doorId" type="xs:positiveInteger"
										use="required" />
									<xs:attribute name="default_status">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="open" />
												<xs:enumeration value="close" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="random_time" type="xs:integer" />
									<xs:attribute name="open_time" type="xs:integer" />
									<xs:attribute name="close_time" type="xs:integer" />
									<xs:attribute name="level" type="xs:nonNegativeInteger" />
									<xs:attribute name="open_method" type="xs:nonNegativeInteger" />
									<xs:attribute name="targetable" type="xs:boolean" />
									<xs:attribute name="check_collision" type="xs:boolean" />
									<xs:attribute name="clanhall_id" type="xs:positiveInteger" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="spawnlist" minOccurs="0">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="group" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="spawn" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="amount" type="xs:positiveInteger" />
												<xs:attribute name="heading" type="xs:integer" use="required" />
												<xs:attribute name="npcId" type="xs:positiveInteger" use="required" />
												<xs:attribute name="onKillDelay" type="xs:nonNegativeInteger" />
												<xs:attribute name="respawn" type="xs:nonNegativeInteger" use="required" />
												<xs:attribute name="respawnRandom" type="xs:nonNegativeInteger" />
												<xs:attribute name="allowRandomWalk" type="xs:boolean" />
												<xs:attribute name="x" type="xs:integer" use="required" />
												<xs:attribute name="y" type="xs:integer" use="required" />
												<xs:attribute name="z" type="xs:integer" use="required" />
												<xs:attribute name="areaName" type="xs:normalizedString" />
												<xs:attribute name="globalMapId" type="xs:positiveInteger" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:normalizedString" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:normalizedString" use="required" />
			<xs:attribute name="ejectTime" type="xs:positiveInteger" />
			<xs:attribute name="allowRandomWalk" type="xs:boolean" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== monkey1sai/l2j-server-datapack/src/main/resources/data/instances/PailakaVarkaSilenosBarracks.xml
<?xml version="1.0" encoding="UTF-8"?>
<instance name="Pailaka (Varka Silenos Barracks)" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/instance.xsd">
	<activityTime val="90" />
	<exitPoint x="143420" y="-59058" z="-3472" />
	<spawnlist>
		<group name="pailaka_2316_npc">
			<!-- Ketra Orc Supporter -->
			<spawn npcId="32502" x="125536" y="-40928" z="-3780" heading="8192" respawn="0" />
			<!-- Ketra Orc Intelligence Officer -->
			<spawn npcId="32509" x="113820" y="-47588" z="-2668" heading="0" respawn="0" />
			<spawn npcId="32509" x="107552" y="-53152" z="-2448" heading="0" respawn="0" />
			<spawn npcId="32509" x="110144" y="-41260" z="-2260" heading="36864" respawn="0" />
		</group>
		<group name="pailaka_2316_boss">
			<!-- Latana -->
			<spawn npcId="18660" x="105785" y="-41785" z="-1810" heading="32768" respawn="0" />
			<!-- Camera -->
			<spawn npcId="18603" x="105785" y="-41785" z="-1810" heading="32768" respawn="0" />
		</group>
		<group name="pailaka_2316_1m1">
		    <spawn npcId="18635" x="122122" y="-45658" z="-2884" heading="0" respawn="0" />
		    <spawn npcId="18636" x="122130" y="-45754" z="-2884" heading="0" respawn="0" />
		    <spawn npcId="18642" x="122134" y="-45862" z="-2884" heading="0" respawn="0" />
		    <spawn npcId="18636" x="122130" y="-45958" z="-2880" heading="0" respawn="0" />
		    <spawn npcId="18635" x="122122" y="-46042" z="-2880" heading="0" respawn="0" />
		</group>
		<group name="pailaka_2316_1m2">
		    <spawn npcId="18640" x="121900" y="-45774" z="-2876" heading="0" respawn="0" />
		    <spawn npcId="18641" x="121898" y="-45904" z="-2875" heading="0" respawn="0" />
		    <spawn npcId="18663" x="121898" y="-45904" z="-2875" heading="0" respawn="0" />
		</group>
		<group name="pailaka_2316_2m1">
		    <spawn npcId="18635" x="117460" y="-51832" z="-2528" heading="57343" respawn="0" />
		    <spawn npcId="18636" x="117396" y="-51928" z="-2520" heading="57343" respawn="0" />
		    <spawn npcId="18642" x="117328" y="-52020" z="-2528" heading="57343" respawn="0" />
		    <spawn npcId="18636" x="117252" y="-52104" z="-2528" heading="57343" respawn="0" />
		    <spawn npcId="18635" x="117180" y="-52180" z="-2528" heading="57343" respawn="0" />
		</group>
		<group name="pailaka_2316_2m2">
		    <spawn npcId="18640" x="117196" y="-51832" z="-2560" heading="57344" respawn="0" />
		    <spawn npcId="18641" x="117088" y="-51948" z="-2544" heading="57344" respawn="0" />
		    <spawn npcId="18663" x="117088" y="-51948" z="-2544" heading="57344" respawn="0" />
		</group>
		<group name="pailaka_2316_3m1">
		    <spawn npcId="18635" x="116024" y="-55796" z="-2512" heading="0" respawn="0" />
		    <spawn npcId="18636" x="116016" y="-55888" z="-2527" heading="0" respawn="0" />
		    <spawn npcId="18642" x="116000" y="-55992" z="-2528" heading="0" respawn="0" />
		    <spawn npcId="18636" x="115984" y="-56092" z="-2512" heading="0" respawn="0" />
		    <spawn npcId="18635" x="115968" y="-56176" z="-2493" heading="0" respawn="0" />
		</group>
		<group name="pailaka_2316_3m2">
		    <spawn npcId="18640" x="115755" y="-55866" z="-2579" heading="0" respawn="0" />
		    <spawn npcId="18641" x="115760" y="-56025" z="-2569" heading="0" respawn="0" />
		    <spawn npcId="18663" x="115760" y="-56025" z="-2569" heading="0" respawn="0" />
		</group>
		<group name="pailaka_2316_4m1">
		    <spawn npcId="18653" x="116150" y="-46307" z="-2614" heading="0" respawn="0" />
		    <spawn npcId="18654" x="116151" y="-46369" z="-2622" heading="0" respawn="0" />
		    <spawn npcId="18646" x="116153" y="-46431" z="-2623" heading="0" respawn="0" />
		    <spawn npcId="18646" x="116152" y="-46491" z="-2631" heading="0" respawn="0" />
		    <spawn npcId="18654" x="116147" y="-46552" z="-2635" heading="0" respawn="0" />
		    <spawn npcId="18653" x="116144" y="-46608" z="-2640" heading="0" respawn="0" />
		</group>
		<group name="pailaka_2316_4m2">
		    <spawn npcId="18645" x="115947" y="-46458" z="-2617" heading="0" respawn="0" />
		    <spawn npcId="18644" x="115911" y="-46378" z="-2623" heading="0" respawn="0" />
		    <spawn npcId="18648" x="115916" y="-46525" z="-2608" heading="0" respawn="0" />
		    <spawn npcId="18663" x="115916" y="-46525" z="-2608" heading="0" respawn="0" />
		</group>
		<group name="pailaka_2316_5m1">
		    <spawn npcId="18653" x="116163" y="-50317" z="-2612" heading="53247" respawn="0" />
		    <spawn npcId="18654" x="116104" y="-50357" z="-2620" heading="53247" respawn="0" />
		    <spawn npcId="18646" x="116048" y="-50397" z="-2622" heading="53247" respawn="0" />
		    <spawn npcId="18646" x="115993" y="-50439" z="-2624" heading="53247" respawn="0" />
		    <spawn npcId="18654" x="115932" y="-50481" z="-2627" heading="53247" respawn="0" />
		    <spawn npcId="18653" x="115869" y="-50505" z="-2609" heading="53247" respawn="0" />
		</group>
		<group name="pailaka_2316_5m2">
		    <spawn npcId="18645" x="116054" y="-50230" z="-2618" heading="53247" respawn="0" />
		    <spawn npcId="18644" x="115944" y="-50297" z="-2624" heading="53247" respawn="0" />
		    <spawn npcId="18648" x="115837" y="-50357" z="-2624" heading="53247" respawn="0" />
		    <spawn npcId="18663" x="115837" y="-50357" z="-2624" heading="53247" respawn="0" />
		</group>
		<group name="pailaka_2316_6m1">
		    <spawn npcId="18653" x="108622" y="-49901" z="-2169" heading="49151" respawn="0" />
		    <spawn npcId="18654" x="108510" y="-49908" z="-2200" heading="49151" respawn="0" />
		    <spawn npcId="18646" x="108398" y="-49916" z="-2229" heading="49151" respawn="0" />
		    <spawn npcId="18646" x="108296" y="-49937" z="-2242" heading="49151" respawn="0" />
		    <spawn npcId="18654" x="108185" y="-49947" z="-2261" heading="49151" respawn="0" />
		    <spawn npcId="18653" x="108078" y="-49950" z="-2268" heading="49151" respawn="0" />
		</group>
		<group name="pailaka_2316_6m2">
		    <spawn npcId="18645" x="108514" y="-49748" z="-2175" heading="45055" respawn="0" />
		    <spawn npcId="18644" x="108322" y="-49726" z="-2214" heading="49151" respawn="0" />
		    <spawn npcId="18648" x="108149" y="-49766" z="-2243" heading="53247" respawn="0" />
		    <spawn npcId="18663" x="108149" y="-49766" z="-2243" heading="53247" respawn="0" />
		</group>
		<group name="pailaka_2316_7m1">
		    <spawn npcId="18649" x="111552" y="-43594" z="-2629" heading="0" respawn="0" />
		    <spawn npcId="18650" x="111549" y="-43688" z="-2616" heading="0" respawn="0" />
		    <spawn npcId="18649" x="111545" y="-43776" z="-2611" heading="0" respawn="0" />
		    <spawn npcId="18650" x="111540" y="-43868" z="-2610" heading="0" respawn="0" />
		    <spawn npcId="18649" x="111536" y="-43952" z="-2606" heading="0" respawn="0" />
		    <spawn npcId="18650" x="111533" y="-44038" z="-2608" heading="0" respawn="0" />
		</group>
		<group name="pailaka_2316_7m2">
		    <spawn npcId="18652" x="111360" y="-43664" z="-2592" heading="0" respawn="0" />
		    <spawn npcId="18648" x="111360" y="-43744" z="-2576" heading="0" respawn="0" />
		    <spawn npcId="18652" x="111344" y="-43824" z="-2576" heading="0" respawn="0" />
		    <spawn npcId="18648" x="111347" y="-43905" z="-2576" heading="0" respawn="0" />
		    <spawn npcId="18652" x="111344" y="-43984" z="-2576" heading="0" respawn="0" />
		    <spawn npcId="18663" x="111344" y="-43984" z="-2576" heading="0" respawn="0" />
		</group>
		<group name="pailaka_2316_8m1">
		    <spawn npcId="18649" x="109081" y="-46337" z="-2176" heading="36864" respawn="0" />
		    <spawn npcId="18650" x="109048" y="-46280" z="-2176" heading="36864" respawn="0" />
		    <spawn npcId="18649" x="109015" y="-46222" z="-2160" heading="36864" respawn="0" />
		    <spawn npcId="18650" x="108984" y="-46168" z="-2160" heading="36864" respawn="0" />
		    <spawn npcId="18649" x="108951" y="-46120" z="-2144" heading="36864" respawn="0" />
		    <spawn npcId="18650" x="108916" y="-46068" z="-2144" heading="36864" respawn="0" />
		</group>
		<group name="pailaka_2316_8m2">
		    <spawn npcId="18652" x="109203" y="-46244" z="-2190" heading="36863" respawn="0" />
		    <spawn npcId="18648" x="109169" y="-46186" z="-2190" heading="36863" respawn="0" />
		    <spawn npcId="18652" x="109134" y="-46127" z="-2174" heading="36863" respawn="0" />
		    <spawn npcId="18648" x="109094" y="-46071" z="-2174" heading="36863" respawn="0" />
		    <spawn npcId="18652" x="109058" y="-46013" z="-2158" heading="36863" respawn="0" />
		    <spawn npcId="18663" x="109058" y="-46013" z="-2158" heading="36863" respawn="0" />
		</group>
		<group name="pailaka_2316_9m1">
		    <spawn npcId="18650" x="110224" y="-39828" z="-1808" heading="49152" respawn="0" />
		    <spawn npcId="18649" x="110144" y="-39840" z="-1840" heading="49152" respawn="0" />
		    <spawn npcId="18650" x="110064" y="-39844" z="-1840" heading="49152" respawn="0" />
		    <spawn npcId="18649" x="109978" y="-39848" z="-1840" heading="49152" respawn="0" />
		    <spawn npcId="18650" x="109892" y="-39847" z="-1824" heading="49152" respawn="0" />
		</group>
		<group name="pailaka_2316_9m2">
		    <spawn npcId="18652" x="110143" y="-39645" z="-1776" heading="49152" respawn="0" />
		    <spawn npcId="18652" x="110048" y="-39648" z="-1776" heading="49152" respawn="0" />
		    <spawn npcId="18652" x="109950" y="-39646" z="-1776" heading="49152" respawn="0" />
		    <spawn npcId="18663" x="109950" y="-39646" z="-1776" heading="49152" respawn="0" />
		</group>
		<group name="pailaka_2316_10m1">
		    <spawn npcId="18655" x="108917" y="-41028" z="-2188" heading="0" respawn="0" />
		    <spawn npcId="18657" x="108912" y="-41089" z="-2180" heading="0" respawn="0" />
		    <spawn npcId="18655" x="108901" y="-41147" z="-2181" heading="0" respawn="0" />
