=== monkey1sai/l2j-server-datapack/src/main/resources/data/xsd/zones.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="zone" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="stat" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="affectedLvlMin" />
												<xs:enumeration value="affectedRace" />
												<xs:enumeration value="allowStore" />
												<xs:enumeration value="castleId" />
												<xs:enumeration value="chance" />
												<xs:enumeration value="clanHallId" />
												<xs:enumeration value="dmgHPSec" />
												<xs:enumeration value="default_enabled" />
												<xs:enumeration value="domainId" />
												<xs:enumeration value="enterMsgId" />
												<xs:enumeration value="fortId" />
												<xs:enumeration value="HpRegenBonus" />
												<xs:enumeration value="initialDelay" />
												<xs:enumeration value="instanceId" />
												<xs:enumeration value="instanceTemplate" />
												<xs:enumeration value="InvadeTime" />
												<xs:enumeration value="leaveMsgId" />
												<xs:enumeration value="maxDynamicSkillCount" />
												<xs:enumeration value="move_bonus" />
												<xs:enumeration value="MpRegenBonus" />
												<xs:enumeration value="NoBookmark" />
												<xs:enumeration value="NoItemDrop" />
												<xs:enumeration value="oustX" />
												<xs:enumeration value="oustY" />
												<xs:enumeration value="oustZ" />
												<xs:enumeration value="residenceId" />
												<xs:enumeration value="residenceZoneId" />
												<xs:enumeration value="restartAllowedTime" />
												<xs:enumeration value="restartTime" />
												<xs:enumeration value="reuse" />
												<xs:enumeration value="showDangerIcon" />
												<xs:enumeration value="skillIdLvl" />
												<xs:enumeration value="spawnMaxX" />
												<xs:enumeration value="spawnMaxY" />
												<xs:enumeration value="spawnMaxZ" />
												<xs:enumeration value="spawnMinX" />
												<xs:enumeration value="spawnMinY" />
												<xs:enumeration value="spawnMinZ" />
												<xs:enumeration value="spawnZ" />
												<xs:enumeration value="targetClass" />
												<xs:enumeration value="taxById" />
												<xs:enumeration value="territoryId" />
												<xs:enumeration value="townId" />
												<xs:enumeration value="expPenaltyPercent" />
												<xs:enumeration value="allowItemDrop" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="val" type="xs:token" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="node" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="X" type="xs:integer" use="required" />
									<xs:attribute name="Y" type="xs:integer" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="race" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="point" type="xs:token" use="required" />
									<xs:attribute name="name" type="xs:token" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="spawn" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="type">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="banish" />
												<xs:enumeration value="blueBanishPoint" />
												<xs:enumeration value="blueStartPoint" />
												<xs:enumeration value="challenger" />
												<xs:enumeration value="chaotic" />
												<xs:enumeration value="entrance" />
												<xs:enumeration value="other" />
												<xs:enumeration value="redBanishPoint" />
												<xs:enumeration value="redStartPoint" />
												<xs:enumeration value="spectatorSpawn" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="X" type="xs:integer" use="required" />
									<xs:attribute name="Y" type="xs:integer" use="required" />
									<xs:attribute name="Z" type="xs:integer" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:positiveInteger" />
						<xs:attribute name="maxZ" type="xs:integer" use="required" />
						<xs:attribute name="minZ" type="xs:integer" use="required" />
						<xs:attribute name="name" type="xs:normalizedString" use="required" />
						<xs:attribute name="rad" type="xs:positiveInteger" />
						<xs:attribute name="shape" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="Cuboid" />
									<xs:enumeration value="Cylinder" />
									<xs:enumeration value="NPoly" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="type" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="ArenaZone" />
									<xs:enumeration value="BossZone" />
									<xs:enumeration value="CastleZone" />
									<xs:enumeration value="ClanHallZone" />
									<xs:enumeration value="CleftZone" />
									<xs:enumeration value="ConditionZone" />
									<xs:enumeration value="DamageZone" />
									<xs:enumeration value="DerbyTrackZone" />
									<xs:enumeration value="EffectZone" />
									<xs:enumeration value="FishingZone" />
									<xs:enumeration value="FortZone" />
									<xs:enumeration value="HqZone" />
									<xs:enumeration value="JailZone" />
									<xs:enumeration value="LandingZone" />
									<xs:enumeration value="MotherTreeZone" />
									<xs:enumeration value="NoDropItemZone" />
									<xs:enumeration value="NoLandingZone" />
									<xs:enumeration value="NoRestartZone" />
									<xs:enumeration value="NoStoreZone" />
									<xs:enumeration value="NoSummonFriendZone" />
									<xs:enumeration value="NpcSpawnTerritory" />
									<xs:enumeration value="OlympiadStadiumZone" />
									<xs:enumeration value="PeaceZone" />
									<xs:enumeration value="ResidenceHallTeleportZone" />
									<xs:enumeration value="ResidenceTeleportZone" />
									<xs:enumeration value="RespawnZone" />
									<xs:enumeration value="ScriptZone" />
									<xs:enumeration value="SiegableHallZone" />
									<xs:enumeration value="SiegeZone" />
									<xs:enumeration value="SwampZone" />
									<xs:enumeration value="TaxZone" />
									<xs:enumeration value="TerritoryWarZone" />
									<xs:enumeration value="TownZone" />
									<xs:enumeration value="WaterZone" />
									<xs:enumeration value="SSQZone" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="enabled" type="xs:boolean" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== monkey1sai/l2j-server-datapack/src/main/resources/data/zones/ssq.xml
<?xml version="1.0" encoding="UTF-8"?>
<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/zones.xsd">
	<!-- SSQ Main Event -->
	<!-- Oracle of Dusk (No Restart Zones) -->
	<zone name="ssq_no_res_1720_01" type="NoRestartZone" shape="NPoly" minZ="-5200" maxZ="-5000">
		<stat name="restartTime" val="0" />
		<node X="-79735" Y="85612" />
		<node X="-78957" Y="85605" />
		<node X="-78957" Y="85690" />
		<node X="-79735" Y="85700" />
	</zone>
	<zone name="ssq_no_res_1720_02" type="NoRestartZone" shape="NPoly" minZ="-5200" maxZ="-5000">
		<stat name="restartTime" val="0" />
		<node X="-80952" Y="85605" />
		<node X="-80139" Y="85597" />
		<node X="-80139" Y="85696" />
		<node X="-80952" Y="85690" />
	</zone>
	<zone name="ssq_no_res_1720_03" type="NoRestartZone" shape="NPoly" minZ="-5192" maxZ="-4992">
		<stat name="restartTime" val="0" />
		<node X="-80962" Y="83695" />
		<node X="-78946" Y="83691" />
		<node X="-78959" Y="85626" />
		<node X="-80947" Y="85625" />
	</zone>
	<zone name="ssq_no_res_1720_04" type="NoRestartZone" shape="NPoly" minZ="-5196" maxZ="-4996">
		<stat name="restartTime" val="0" />
		<node X="-81199" Y="87363" />
		<node X="-80386" Y="87358" />
		<node X="-80386" Y="87449" />
		<node X="-81203" Y="87454" />
	</zone>
	<zone name="ssq_no_res_1720_05" type="NoRestartZone" shape="NPoly" minZ="-5196" maxZ="-4996">
		<stat name="restartTime" val="0" />
		<node X="-79990" Y="87361" />
		<node X="-79212" Y="87360" />
		<node X="-79212" Y="87460" />
		<node X="-79989" Y="87446" />
	</zone>
	<zone name="ssq_no_res_1720_06" type="NoRestartZone" shape="NPoly" minZ="-5200" maxZ="-5000">
		<stat name="restartTime" val="0" />
		<node X="-81205" Y="87433" />
		<node X="-79212" Y="87432" />
		<node X="-79208" Y="89361" />
		<node X="-81207" Y="89361" />
	</zone>
	<zone name="ssq_no_res_1720_07" type="NoRestartZone" shape="NPoly" minZ="-5200" maxZ="-5000">
		<stat name="restartTime" val="0" />
		<node X="-78197" Y="87968" />
		<node X="-77373" Y="87961" />
		<node X="-77365" Y="88060" />
		<node X="-78197" Y="88060" />
	</zone>
	<zone name="ssq_no_res_1720_08" type="NoRestartZone" shape="NPoly" minZ="-5200" maxZ="-5000">
		<stat name="restartTime" val="0" />
		<node X="-77025" Y="87959" />
		<node X="-76209" Y="87969" />
		<node X="-76202" Y="88069" />
		<node X="-77026" Y="88061" />
	</zone>
	<zone name="ssq_no_res_1720_09" type="NoRestartZone" shape="NPoly" minZ="-5196" maxZ="-4996">
		<stat name="restartTime" val="0" />
		<node X="-78196" Y="88060" />
		<node X="-76200" Y="88068" />
		<node X="-76192" Y="89970" />
		<node X="-78196" Y="89970" />
	</zone>
	<zone name="ssq_no_res_1720_10" type="NoRestartZone" shape="NPoly" minZ="-5204" maxZ="-5004">
		<stat name="restartTime" val="0" />
		<node X="-76797" Y="86142" />
		<node X="-75947" Y="86147" />
		<node X="-75945" Y="86304" />
		<node X="-76794" Y="86298" />
	</zone>
	<zone name="ssq_no_res_1720_11" type="NoRestartZone" shape="NPoly" minZ="-5196" maxZ="-4996">
		<stat name="restartTime" val="0" />
		<node X="-77944" Y="86148" />
		<node X="-77189" Y="86148" />
		<node X="-77194" Y="86291" />
		<node X="-77942" Y="86295" />
	</zone>
	<zone name="ssq_no_res_1720_12" type="NoRestartZone" shape="NPoly" minZ="-5196" maxZ="-4996">
		<stat name="restartTime" val="0" />
		<node X="-77949" Y="84300" />
		<node X="-75940" Y="84300" />
		<node X="-75943" Y="86185" />
		<node X="-77939" Y="86187" />
	</zone>
	<zone name="ssq_no_res_1720_13" type="NoRestartZone" shape="NPoly" minZ="-5200" maxZ="-5000">
		<stat name="restartTime" val="0" />
		<node X="-75870" Y="87311" />
		<node X="-75738" Y="87309" />
		<node X="-75738" Y="88130" />
		<node X="-75870" Y="88125" />
	</zone>
	<zone name="ssq_no_res_1720_14" type="NoRestartZone" shape="NPoly" minZ="-5200" maxZ="-5000">
		<stat name="restartTime" val="0" />
		<node X="-75865" Y="86137" />
		<node X="-75747" Y="86134" />
		<node X="-75740" Y="86958" />
		<node X="-75865" Y="86963" />
	</zone>
	<zone name="ssq_no_res_1720_15" type="NoRestartZone" shape="NPoly" minZ="-5200" maxZ="-5000">
		<stat name="restartTime" val="0" />
		<node X="-75758" Y="86126" />
		<node X="-73857" Y="86139" />
		<node X="-73855" Y="88140" />
		<node X="-75769" Y="88133" />
	</zone>
	<!-- Oracle of Dawn (No Restart Zones) -->
	<zone name="ssq_no_res_1721_01" type="NoRestartZone" shape="NPoly" minZ="-4948" maxZ="-4748">
		<stat name="restartTime" val="0" />
		<node X="-78713" Y="110409" />
		<node X="-77923" Y="110423" />
		<node X="-77923" Y="110522" />
		<node X="-78708" Y="110515" />
	</zone>
	<zone name="ssq_no_res_1721_02" type="NoRestartZone" shape="NPoly" minZ="-4940" maxZ="-4740">
		<stat name="restartTime" val="0" />
		<node X="-79923" Y="110427" />
		<node X="-79109" Y="110432" />
		<node X="-79105" Y="110524" />
		<node X="-79923" Y="110528" />
	</zone>
	<zone name="ssq_no_res_1721_03" type="NoRestartZone" shape="NPoly" minZ="-4944" maxZ="-4744">
		<stat name="restartTime" val="0" />
		<node X="-79931" Y="108523" />
		<node X="-77928" Y="108523" />
		<node X="-77932" Y="110445" />
		<node X="-79925" Y="110453" />
	</zone>
	<zone name="ssq_no_res_1721_04" type="NoRestartZone" shape="NPoly" minZ="-4940" maxZ="-4740">
		<stat name="restartTime" val="0" />
		<node X="-75761" Y="111051" />
		<node X="-74921" Y="111033" />
		<node X="-74921" Y="111142" />
		<node X="-75757" Y="111151" />
	</zone>
	<zone name="ssq_no_res_1721_05" type="NoRestartZone" shape="NPoly" minZ="-4940" maxZ="-4740">
		<stat name="restartTime" val="0" />
		<node X="-76920" Y="111022" />
		<node X="-76089" Y="111022" />
		<node X="-76085" Y="111105" />
		<node X="-76920" Y="111097" />
	</zone>
	<zone name="ssq_no_res_1721_06" type="NoRestartZone" shape="NPoly" minZ="-4932" maxZ="-4732">
		<stat name="restartTime" val="0" />
		<node X="-76920" Y="109134" />
		<node X="-74928" Y="109134" />
		<node X="-74920" Y="111099" />
		<node X="-76920" Y="111087" />
	</zone>
	<zone name="ssq_no_res_1721_07" type="NoRestartZone" shape="NPoly" minZ="-4944" maxZ="-4744">
		<stat name="restartTime" val="0" />
		<node X="-77176" Y="112795" />
		<node X="-76350" Y="112795" />
		<node X="-76344" Y="112897" />
		<node X="-77176" Y="112903" />
	</zone>
	<zone name="ssq_no_res_1721_08" type="NoRestartZone" shape="NPoly" minZ="-4940" maxZ="-4740">
		<stat name="restartTime" val="0" />
		<node X="-76002" Y="112810" />
		<node X="-75182" Y="112806" />
		<node X="-75176" Y="112904" />
		<node X="-76002" Y="112898" />
	</zone>
	<zone name="ssq_no_res_1721_09" type="NoRestartZone" shape="NPoly" minZ="-4944" maxZ="-4744">
		<stat name="restartTime" val="0" />
		<node X="-77174" Y="112902" />
		<node X="-75172" Y="112902" />
		<node X="-75167" Y="114798" />
		<node X="-77173" Y="114806" />
	</zone>
	<zone name="ssq_no_res_1721_10" type="NoRestartZone" shape="NPoly" minZ="-4940" maxZ="-4740">
		<stat name="restartTime" val="0" />
		<node X="-80178" Y="112233" />
		<node X="-79362" Y="112250" />
		<node X="-79356" Y="112294" />
		<node X="-80190" Y="112301" />
	</zone>
	<zone name="ssq_no_res_1721_11" type="NoRestartZone" shape="NPoly" minZ="-4940" maxZ="-4740">
		<stat name="restartTime" val="0" />
		<node X="-78861" Y="112220" />
		<node X="-78196" Y="112201" />
		<node X="-78178" Y="112294" />
		<node X="-78994" Y="112294" />
	</zone>
	<zone name="ssq_no_res_1721_12" type="NoRestartZone" shape="NPoly" minZ="-4940" maxZ="-4740">
		<stat name="restartTime" val="0" />
		<node X="-80184" Y="112276" />
		<node X="-78188" Y="112262" />
		<node X="-78176" Y="114188" />
		<node X="-80190" Y="114196" />
	</zone>
	<zone name="ssq_no_res_1721_13" type="NoRestartZone" shape="NPoly" minZ="-4940" maxZ="-4740">
		<stat name="restartTime" val="0" />
		<node X="-74840" Y="112152" />
		<node X="-74704" Y="112157" />
		<node X="-74707" Y="112966" />
		<node X="-74840" Y="112966" />
	</zone>
	<zone name="ssq_no_res_1721_14" type="NoRestartZone" shape="NPoly" minZ="-4948" maxZ="-4748">
		<stat name="restartTime" val="0" />
		<node X="-74840" Y="110962" />
		<node X="-74737" Y="110962" />
		<node X="-74741" Y="111793" />
		<node X="-74840" Y="111796" />
	</zone>
	<zone name="ssq_no_res_1721_15" type="NoRestartZone" shape="NPoly" minZ="-4936" maxZ="-4736">
		<stat name="restartTime" val="0" />
		<node X="-74737" Y="110969" />
		<node X="-72838" Y="110964" />
		<node X="-72830" Y="112974" />
		<node X="-74740" Y="112965" />
	</zone>
	<!-- Oracle of Dusk (Mp Regen Zones) -->
	<zone name="ssq_main_event_17_20_01" type="MotherTreeZone" shape="NPoly" minZ="-5168" maxZ="-4968">
		<stat name="MpRegenBonus" val="2" />
		<stat name="enterMsgId" val="1054" />
		<stat name="leaveMsgId" val="1055" />
		<node X="-79956" Y="84556" />
		<node X="-79832" Y="84620" />
		<node X="-79824" Y="84772" />
		<node X="-79956" Y="84844" />
		<node X="-80080" Y="84772" />
		<node X="-80076" Y="84620" />
	</zone>
	<zone name="ssq_main_event_17_20_04" type="MotherTreeZone" shape="NPoly" minZ="-5164" maxZ="-4964">
		<stat name="MpRegenBonus" val="2" />
		<stat name="enterMsgId" val="1054" />
		<stat name="leaveMsgId" val="1055" />
		<node X="-76936" Y="85164" />
		<node X="-76820" Y="85232" />
		<node X="-76816" Y="85380" />
		<node X="-76948" Y="85444" />
		<node X="-77068" Y="85376" />
		<node X="-77068" Y="85236" />
	</zone>
	<zone name="ssq_main_event_17_20_05" type="MotherTreeZone" shape="NPoly" minZ="-5164" maxZ="-4964">
		<stat name="MpRegenBonus" val="3" />
		<stat name="enterMsgId" val="1054" />
		<stat name="leaveMsgId" val="1055" />
		<node X="-74924" Y="87012" />
		<node X="-74784" Y="87008" />
		<node X="-74712" Y="87132" />
		<node X="-74780" Y="87256" />
		<node X="-74924" Y="87260" />
		<node X="-75000" Y="87140" />
	</zone>
